apiVersion: v1
kind: Pod
metadata:
  name: db-mysql
  labels:
    app: database
spec:
  containers:
    - name: db-mysql
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef: 
            name: db-configmap